#pragma once
#define BLOCK_HEIGHT 20
#define BLOCK_WIDTH  30

#define BLOCK_ROWS_COUNT 7
#define BLOCK_V_OFFSET   120
#define BLOCK_H_OFFSET   90
#define BETWEEN_BLOCKS_H_OFFSET 5
#define BETWEEN_BLOCKS_V_OFFSET 5

#define START_ROCKET_SIZE     200
#define ROCKET_BOTTOM_OFSET   40
#define START_ROCKET_H_OFFSET 200
#define START_ROCKET_HEIGHT   12

#define BALL_RADIUS 10
#define BALL_COLOR { 1, 0.7, 0.4 }